export const translations = {
  bg: {
    nav_gallery: 'Галерия', nav_services: 'Услуги', nav_about: 'За нас',
    nav_process: 'Процес', nav_contact: 'Контакти', nav_cta: 'Консултация',
    hero_tag: 'Ръчно изработени кухни',
    hero_h1: 'Всяка кухня разказва своя <em>история</em>',
    hero_sub: 'Кухненско обзавеждане по поръчка, проектирано да издържи поколения. Всяко парче — с любов, прецизност и най-добрите материали.',
    hero_btn1: 'Вижте нашите проекти', hero_btn2: 'Запитване',
    stat1: 'изработени кухни', stat2: 'опит в занаята', stat3: 'оценка от клиенти',
    review_quote: '"Невероятна изработка"',
    review_text: 'Вниманието към детайла е изключително. Кухнята ни стана сърцето на дома.',
    review_author: '— Мария К., София',
    serv_eyebrow: 'Услуги',
    serv_h2: 'Правим <em>кухни по поръчка</em>',
    serv_body: 'Специализираме в изработка на кухненско обзавеждане по поръчка — от проектирането до монтажа. Всяка кухня е направена по вашите размери, в стила и материалите, които желаете.',
    serv_gallery_link: 'Вижте нашите проекти →',
    test_eyebrow: 'Какво казват клиентите',
    test_h2: 'Изградено на доверие,<br>завършено с гордост',
    t1_text: 'От първата консултация до монтажа — всичко беше безупречно. Кухнята ни изглежда като от списание за интериорен дизайн.',
    t1_name: 'Мария Костадинова', t1_loc: 'Пловдив — Модерно обновяване',
    t2_text: 'Дадохме им трудно Г-образно пространство и те го превърнаха в най-функционалната и красива кухня, която сме имали.',
    t2_name: 'Георги Петров', t2_loc: 'София — Пълно обзавеждане',
    t3_text: 'Масивните дъбови шкафове изглеждат нови и след пет години. Качеството е наистина изключително.',
    t3_name: 'Елена Маринова', t3_loc: 'Варна — Кухня по поръчка',
    cta_h2: 'Готови за кухня,<br>която ще <em>обичате завинаги?</em>',
    cta_sub: 'Запишете безплатна консултация — без ангажимент, само вдъхновение и експертен съвет.',
    cta_btn: 'Запишете се сега →',
    footer_tag: 'Ръчно изработено кухненско обзавеждане с любов в България.',
    fc1_title: 'Услуги', fc1_1: 'Кухни по поръчка', fc1_2: 'Кухненски острови', fc1_3: 'Работни плотове', fc1_4: 'Пълно обзавеждане', fc1_5: 'Ремонт и обновяване',
    fc2_title: 'Компания', fc2_1: 'За нас', fc2_2: 'Нашият процес', fc2_3: 'Галерия', fc2_4: 'Отзиви',
    fc3_title: 'Контакти', fc3_1: 'Безплатна оферта', fc3_2: 'Viber', fc3_3: '+359 88 9567999',
    footer_copy: '© 2026 Wood&Craft. Всички права запазени.',
    footer_links: 'Политика за поверителност · Условия',
    wa_text: 'Viber',
    page_eyebrow: 'Нашата работа',
    page_h1: 'Всяка кухня,<br>един <em>шедьовър</em>',
    page_sub: 'Разгледайте нашето портфолио от ръчно изработени кухни.',
    filter_all: 'Всички', filter_modern: 'Модерен', filter_classic: 'Класически',
    filter_rustic: 'Дърво и камък', filter_minimal: 'Минималистичен', filter_industrial: 'Двуцветен',
    lb_material: 'Материал', lb_size: 'Населено място', lb_timeline: 'Стил',
    lb_cta: 'Запитайте за подобен проект →',
    projects_label: 'проекта',
    proc_eyebrow: 'Как работим',
    proc_h1: 'От идея до <em>завършена кухня</em> за 2 седмици',
    proc_sub: 'Прецизен процес — качество, яснота и спокойствие от началото до края.',
    badge1: 'Безплатна консултация', badge2: 'Фиксирана цена', badge3: '10-год. гаранция',
    tab_w1: 'Седмица 1', tab_w2: 'Седмица 2',
    w1_label: 'Ден 1 – 7 · Планиране и проектиране',
    w2_label: 'Ден 8 – 14 · Производство и монтаж',
    d1_num:'Ден 1', d1_title:'Безплатна консултация', d1_desc:'Посещение у вас. Обсъждаме желанията, стила и бюджета.',
    d2_num:'Ден 2', d2_title:'Измерване', d2_desc:'Прецизно измерване на всички стени, ъгли и инсталации.',
    d3_num:'Ден 3 – 4', d3_title:'3D проект и оферта', d3_desc:'Изготвяме 3D визуализация и финална оферта с фиксирана цена.',
    d4_num:'Ден 5', d4_title:'Избор на материали', d4_desc:'Посещение в шоурума. Избирате дърво, цвят и фурнитура.',
    d5_num:'Ден 6 – 7', d5_title:'Одобрение и договор', d5_desc:'Финализираме дизайна. Подписваме договор с фиксирана цена.',
    d6_num:'Ден 8 – 9', d6_title:'Рязане и обработка', d6_desc:'CNC рязане на панелите. Обработка на ръбовете и повърхностите.',
    d7_num:'Ден 10', d7_title:'Сглобяване', d7_desc:'Ръчно сглобяване на всички шкафове и корпуси от майстора.',
    d8_num:'Ден 11', d8_title:'Контрол на качеството', d8_desc:'Проверка на всеки детайл — размери, покритие, механизми.',
    d9_num:'Ден 12 – 13', d9_title:'Доставка и монтаж', d9_desc:'Внимателна доставка и професионален монтаж на място.',
    d10_num:'Ден 14', d10_title:'Предаване и гаранция', d10_desc:'Финален преглед заедно. Предаване на гаранционна карта.',
    guar_eyebrow:'Нашите обещания', guar_h2:'Защо клиентите ни <em>се доверяват</em>',
    gg1_title:'10-годишна гаранция', gg1_text:'Ако нещо се счупи — ние го оправяме.',
    gg2_title:'Фиксирана цена', gg2_text:'Без скрити разходи, без изненади в края.',
    gg3_title:'Спазен срок', gg3_text:'280+ проекта — никога не сме закъснявали.',
    gg4_title:'Пряка комуникация', gg4_text:'Директна връзка с майстора — Viber, телефон или имейл.',
    faq_eyebrow:'Чести въпроси', faq_h2:'Имате <em>въпроси?</em>',
    faq1_q:'Наистина ли е възможно за 2 седмици?', faq1_a:'Да — при стандартна кухня до 25 м². Имаме собствена работилница с CNC оборудване.',
    faq2_q:'Какво се случва ако не съм доволен от проекта?', faq2_a:'Правим толкова ревизии, колкото са необходими. Производството започва само след пълно одобрение.',
    faq3_q:'Монтирате ли и уредите?', faq3_a:'Монтираме вградените уреди. ВиК и ел. свързване е от лицензиран специалист.',
    faq4_q:'Трябва ли да присъствам по време на монтажа?', faq4_a:'Не е задължително. Препоръчваме при началото и финалния преглед.',
    faq5_q:'Какви материали използвате?', faq5_a:'Масивна дървесина, ПДЧ Egger, лакирани МДФ и акрил. Плотове от гранит, кварц, мрамор или дърво.',
    faq6_q:'Има ли депозит при подписване?', faq6_a:'50% депозит при подписване. Останалите 50% след успешния монтаж.',
    pcta_h2:'Готови да стартирате<br>вашия <em>проект?</em>', pcta_sub:'Запишете безплатна консултация — ще дойдем при вас.',
    contact_eyebrow: 'Свържете се с нас',
    contact_h2: 'Нека създадем<br>вашата <em>кухня</em>',
    contact_sub: 'Попълнете формата или се свържете директно. Отговаряме до 2 часа.',
    form_name: 'Три имена', form_phone: 'Телефон', form_email: 'Имейл адрес',
    form_city: 'Град', form_size: 'Приблизителна площ (кв.м)',
    form_message: 'Разкажете ни за проекта',
    form_submit: 'Изпратете запитване →',
    form_success: 'Получихме вашето запитване! Ще се свържем с вас до 2 часа.',
    form_error: 'Нещо се обърка. Моля опитайте отново или се свържете директно.',
    contact_viber: 'Пишете във Viber',
    contact_phone: '+359 88 9567999',
    contact_email: 'hello@woodcraft.bg',
  },
  en: {
    nav_gallery: 'Gallery', nav_services: 'Services', nav_about: 'About',
    nav_process: 'Process', nav_contact: 'Contact', nav_cta: 'Consultation',
    hero_tag: 'Handcrafted kitchen furniture',
    hero_h1: 'Where every kitchen tells a <em>story</em>',
    hero_sub: 'Bespoke kitchen furniture designed to last generations. Every piece crafted with passion, precision, and the finest materials.',
    hero_btn1: 'View Our Work', hero_btn2: 'Get a Quote',
    stat1: 'kitchens completed', stat2: 'years of craft', stat3: 'client rating',
    review_quote: '"Absolutely stunning work"',
    review_text: 'The attention to detail is incredible. Our kitchen became the heart of our home.',
    review_author: '— Maria K., Sofia',
    serv_eyebrow: 'Services',
    serv_h2: 'We make <em>bespoke kitchens</em>',
    serv_body: 'We specialise in custom kitchen furniture — from design to installation. Every kitchen is built to your exact dimensions, in the style and materials you choose.',
    serv_gallery_link: 'View our projects →',
    test_eyebrow: 'What clients say',
    test_h2: 'Built on trust,<br>finished with pride',
    t1_text: 'From the first consultation to installation — everything was flawless. Our kitchen looks like something from an interior design magazine.',
    t1_name: 'Maria Kostadinova', t1_loc: 'Plovdiv — Modern renovation',
    t2_text: "We gave them a tricky L-shaped space and they turned it into the most functional, beautiful kitchen we've ever had.",
    t2_name: 'Georgi Petrov', t2_loc: 'Sofia — Full kitchen fit-out',
    t3_text: 'The solid oak cabinets still look brand new five years later. The quality is genuinely exceptional.',
    t3_name: 'Elena Marinova', t3_loc: 'Varna — Bespoke cabinetry',
    cta_h2: "Ready for a kitchen<br>you'll <em>love forever?</em>",
    cta_sub: 'Book a free design consultation — no pressure, just inspiration and expert advice.',
    cta_btn: 'Book Now →',
    footer_tag: 'Handcrafted kitchen furniture made with passion in Bulgaria.',
    fc1_title: 'Services', fc1_1: 'Custom Cabinetry', fc1_2: 'Kitchen Islands', fc1_3: 'Worktops', fc1_4: 'Full Fit-Out', fc1_5: 'Renovation',
    fc2_title: 'Company', fc2_1: 'About Us', fc2_2: 'Our Process', fc2_3: 'Gallery', fc2_4: 'Testimonials',
    fc3_title: 'Contact', fc3_1: 'Free Quote', fc3_2: 'Viber', fc3_3: '+359 88 9567999',
    footer_copy: '© 2026 Wood&Craft. All rights reserved.',
    footer_links: 'Privacy Policy · Terms',
    wa_text: 'Viber',
    page_eyebrow: 'Our work',
    page_h1: 'Every kitchen,<br>a <em>masterpiece</em>',
    page_sub: 'Browse our portfolio of handcrafted kitchens.',
    filter_all: 'All', filter_modern: 'Modern', filter_classic: 'Classic',
    filter_rustic: 'Wood & Stone', filter_minimal: 'Minimalist', filter_industrial: 'Two-tone',
    lb_material: 'Material', lb_size: 'Location', lb_timeline: 'Style',
    lb_cta: 'Request a similar quote →',
    projects_label: 'projects',
    proc_eyebrow: 'How we work',
    proc_h1: 'From idea to <em>finished kitchen</em> in 2 weeks',
    proc_sub: 'A precise process — quality, clarity and peace of mind from start to finish.',
    badge1: 'Free consultation', badge2: 'Fixed price', badge3: '10-yr warranty',
    tab_w1: 'Week 1', tab_w2: 'Week 2',
    w1_label: 'Day 1 – 7 · Planning & design',
    w2_label: 'Day 8 – 14 · Production & installation',
    d1_num:'Day 1', d1_title:'Free consultation', d1_desc:'A visit to your home. We discuss your wishes, style and budget.',
    d2_num:'Day 2', d2_title:'Measurement', d2_desc:'Precise measurement of all walls, angles and installations.',
    d3_num:'Day 3 – 4', d3_title:'3D design & quote', d3_desc:'We create a 3D visualisation and a fixed-price quote.',
    d4_num:'Day 5', d4_title:'Material selection', d4_desc:'Showroom visit. You choose wood, colour and hardware.',
    d5_num:'Day 6 – 7', d5_title:'Approval & contract', d5_desc:'We finalise the design and sign a fixed-price contract.',
    d6_num:'Day 8 – 9', d6_title:'Cutting & processing', d6_desc:'CNC cutting of panels. Edge banding and surface processing.',
    d7_num:'Day 10', d7_title:'Assembly', d7_desc:'Hand assembly of all cabinets and carcasses by our craftsman.',
    d8_num:'Day 11', d8_title:'Quality control', d8_desc:'Check of every detail — dimensions, finish, mechanisms.',
    d9_num:'Day 12 – 13', d9_title:'Delivery & installation', d9_desc:'Careful delivery and professional on-site installation.',
    d10_num:'Day 14', d10_title:'Handover & warranty', d10_desc:'Final walkthrough together. Warranty card handed over.',
    guar_eyebrow:'Our promises', guar_h2:'Why clients <em>trust us</em>',
    gg1_title:'10-year warranty', gg1_text:'If something breaks — we fix it.',
    gg2_title:'Fixed price', gg2_text:'No hidden costs, no surprises at the end.',
    gg3_title:'On-time delivery', gg3_text:'280+ projects — never been late.',
    gg4_title:'Direct communication', gg4_text:'Direct contact with the craftsman — Viber, phone or email.',
    faq_eyebrow:'FAQ', faq_h2:'Got <em>questions?</em>',
    faq1_q:'Is 2 weeks really possible?', faq1_a:'Yes — for a standard kitchen up to 25 m². We have our own workshop with CNC equipment.',
    faq2_q:'What if I am not happy with the design?', faq2_a:'We do as many revisions as needed. Production only starts after your full approval.',
    faq3_q:'Do you install the appliances too?', faq3_a:'We install built-in appliances. Plumbing and electrical connections are done by a licensed specialist.',
    faq4_q:'Do I need to be present during installation?', faq4_a:"Not the whole time. We recommend being there at the start and final walkthrough.",
    faq5_q:'What materials do you use?', faq5_a:'Solid wood (oak, walnut), Egger MDF, lacquered panels. Worktops in granite, quartz, marble or wood.',
    faq6_q:'Is there a deposit when signing?', faq6_a:'50% deposit on signing. The remaining 50% after successful installation.',
    pcta_h2:'Ready to start<br>your <em>project?</em>', pcta_sub:'Book a free consultation — we will come to you.',
    contact_eyebrow: 'Get in touch',
    contact_h2: "Let's create<br>your <em>kitchen</em>",
    contact_sub: 'Fill in the form or reach us directly. We respond within 2 hours.',
    form_name: 'Full name', form_phone: 'Phone number', form_email: 'Email address',
    form_city: 'City', form_size: 'Approximate kitchen size (m²)',
    form_message: 'Tell us about your project',
    form_submit: 'Send enquiry →',
    form_success: 'We received your enquiry! We will be in touch within 2 hours.',
    form_error: 'Something went wrong. Please try again or contact us directly.',
    contact_viber: 'Chat on Viber',
    contact_phone: '+359 88 9567999',
    contact_email: 'hello@woodcraft.bg',
  },
}
